
  
export const sc = {
    card: {
      padding:    '20px',
      flex:       1,
      minWidth:   160,
      transition: 'var(--transition)',
    },
    iconRow: {
      display:        'flex',
      justifyContent: 'space-between',
      alignItems:     'center',
      marginBottom:   12,
    },
    icon: {
      width:          36,
      height:         36,
      borderRadius:   'var(--radius-md)',
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
    },
    value: {
      fontSize:      22,
      fontFamily:    'var(--font-mono)',
      fontWeight:    700,
      marginBottom:  4,
      letterSpacing: '-0.02em',
    },
    sub: {
      fontSize:   12,
      fontFamily: 'var(--font-mono)',
      fontWeight: 600,
      marginBottom: 4,
    },
    label: {
      fontSize:   11,
      color:      'var(--text-muted)',
      fontFamily: 'var(--font-mono)',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
    },
}
  
export const ml = {
    card: {
      flex:    1,
      padding: '20px',
    },
    header: {
      display:        'flex',
      justifyContent: 'space-between',
      alignItems:     'center',
      marginBottom:   16,
    },
    title: {
      fontFamily:    'var(--font-display)',
      fontSize:      14,
      fontWeight:    700,
      color:         'var(--text-primary)',
      letterSpacing: '-0.01em',
    },
    dot: {
      width:        8,
      height:       8,
      borderRadius: '50%',
    },
    row: {
      display:        'flex',
      alignItems:     'center',
      padding:        '8px 0',
      borderBottom:   '1px solid var(--border-primary)',
      gap:            8,
    },
    ticker: {
      flex:          1,
      fontSize:      13,
      fontFamily:    'var(--font-mono)',
      fontWeight:    700,
      color:         'var(--text-primary)',
      letterSpacing: '0.04em',
    },
    price: {
      fontSize:   13,
      fontFamily: 'var(--font-mono)',
      color:      'var(--text-secondary)',
    },
    pct: {
      fontSize:      12,
      fontFamily:    'var(--font-mono)',
      fontWeight:    700,
      minWidth:      60,
      textAlign:     'right',
    },
}
  


export const s = {
    root: { minHeight: '100vh', background: 'var(--bg-primary)' },
    page: { marginLeft: 240, padding: '32px 28px', maxWidth: 1400 },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 8,
      flexWrap: 'wrap',
      gap: 16,
    },
    title: {
      fontSize: 28,
      letterSpacing: '-0.02em',
      marginBottom: 4,
    },
    subtitle: {
      fontSize: 13,
      fontFamily: 'var(--font-mono)',
      color: 'var(--text-secondary)',
    },
    headerRight: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
    },
    wsStatus: {
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      marginBottom: 24,
    },
    wsDot: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      transition: 'var(--transition)',
    },
    wsText: {
      fontSize: 11,
      fontFamily: 'var(--font-mono)',
      color: 'var(--text-muted)',
      letterSpacing: '0.06em',
    },
    summaryStrip: {
      display: 'flex',
      gap: 16,
      marginBottom: 24,
      flexWrap: 'wrap',
    },
    marginCallBanner: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: 12,
      background: 'var(--loss-dim)',
      border: '1px solid var(--loss)',
      borderRadius: 'var(--radius-lg)',
      padding: '16px 20px',
      color: 'var(--loss)',
      marginBottom: 24,
      fontFamily: 'var(--font-mono)',
      fontSize: 14,
    },
    glRow: {
      display: 'flex',
      gap: 16,
      marginBottom: 24,
      flexWrap: 'wrap',
    },
    sectionHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 20,
      letterSpacing: '-0.02em',
    },
    stockCount: {
      fontSize: 11,
      fontFamily: 'var(--font-mono)',
      color: 'var(--text-muted)',
      background: 'var(--bg-card)',
      border: '1px solid var(--border-primary)',
      borderRadius: 20,
      padding: '2px 10px',
      letterSpacing: '0.06em',
    },
    stockGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
      gap: 16,
      paddingBottom: 40,
    },
    modalOverlay: {
      position: 'fixed',
      inset: 0,
      background: 'rgba(0,0,0,0.7)',
      backdropFilter: 'blur(4px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: 24,
    },
    modalCard: {
      background: 'var(--bg-card)',
      border: '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-xl)',
      width: '100%',
      maxWidth: 480,
      boxShadow: 'var(--shadow-card), var(--shadow-glow-cyan)',
      overflow: 'hidden',
    },
    modalHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '20px 24px',
      borderBottom: '1px solid var(--border-primary)',
    },
    modalTitle: {
      fontSize: 16,
      fontFamily: 'var(--font-display)',
      letterSpacing: '-0.01em',
    },
    closeBtn: {
      background: 'var(--bg-input)',
      border: '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-md)',
      width: 32,
      height: 32,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      color: 'var(--text-secondary)',
      transition: 'var(--transition)',
    },
}