export const s = {
    root:    { minHeight: '100vh', background: 'var(--bg-primary)' },
    page:    { marginLeft: 240, padding: '32px 28px', maxWidth: 1400 },
    header: {
      display:        'flex',
      justifyContent: 'space-between',
      alignItems:     'flex-start',
      marginBottom:   24,
    },
    title:    { fontSize: 28, letterSpacing: '-0.02em', marginBottom: 4 },
    subtitle: {
      fontSize:   13,
      fontFamily: 'var(--font-mono)',
      color:      'var(--text-secondary)',
    },
    marginCallBanner: {
      display:      'flex',
      alignItems:   'flex-start',
      gap:          12,
      background:   'var(--loss-dim)',
      border:       '1px solid var(--loss)',
      borderRadius: 'var(--radius-lg)',
      padding:      '16px 20px',
      color:        'var(--loss)',
      marginBottom: 24,
      fontFamily:   'var(--font-mono)',
      fontSize:     14,
    },
    statsRow: {
      display:      'flex',
      gap:          16,
      marginBottom: 24,
      flexWrap:     'wrap',
    },
    mainRow: {
      display:      'flex',
      gap:          16,
      marginBottom: 24,
      flexWrap:     'wrap',
    },
    chartCard: {
      flex:     '2 1 300px',
      padding:  '24px',
      position: 'relative',
    },
    cardTitle: {
      fontFamily:    'var(--font-display)',
      fontSize:      15,
      fontWeight:    700,
      letterSpacing: '-0.01em',
      marginBottom:  16,
    },
    pieCenter: {
      position:      'absolute',
      top:           '50%',
      left:          '35%',
      transform:     'translate(-50%, -10%)',
      textAlign:     'center',
      pointerEvents: 'none',
    },
    pieCenterValue: {
      display:       'block',
      fontFamily:    'var(--font-mono)',
      fontSize:      14,
      fontWeight:    700,
      color:         'var(--text-primary)',
    },
    pieCenterLabel: {
      display:       'block',
      fontFamily:    'var(--font-mono)',
      fontSize:      10,
      color:         'var(--text-muted)',
      letterSpacing: '0.06em',
    },
    marginCard:  { flex: '1 1 220px', padding: '24px' },
    marginRows:  { display: 'flex', flexDirection: 'column', marginBottom: 16 },
    marginBarTrack: {
      height:       6,
      background:   'var(--bg-input)',
      borderRadius: 3,
      overflow:     'hidden',
      marginBottom: 6,
    },
    marginBarFill: {
      height:       '100%',
      borderRadius: 3,
      transition:   'var(--transition-slow)',
    },
    marginBarLabel: {
      fontSize:   11,
      fontFamily: 'var(--font-mono)',
      color:      'var(--text-muted)',
      textAlign:  'right',
    },
    tabRow: {
      display:       'flex',
      gap:           4,
      marginBottom:  16,
      borderBottom:  '1px solid var(--border-primary)',
      paddingBottom: 0,
    },
    tab: {
      display:       'flex',
      alignItems:    'center',
      gap:           6,
      padding:       '10px 18px',
      background:    'none',
      border:        'none',
      borderBottom:  '2px solid transparent',
      cursor:        'pointer',
      fontFamily:    'var(--font-ui)',
      fontSize:      13,
      fontWeight:    700,
      color:         'var(--text-muted)',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      transition:    'var(--transition)',
      marginBottom:  '-1px',
    },
    tabActive: {
      color:             'var(--accent-cyan)',
      borderBottomColor: 'var(--accent-cyan)',
    },
    tabBadge: {
      background:     'var(--accent-amber)',
      color:          'var(--bg-primary)',
      borderRadius:   '50%',
      width:          18,
      height:         18,
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
      fontSize:       10,
      fontWeight:     700,
    },
    tableWrapper: { marginBottom: 40 },
  
    // ── Modal styles ──
    modalOverlay: {
      position:       'fixed',
      inset:          0,
      background:     'rgba(0,0,0,0.6)',
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
      zIndex:         1000,
    },
    modalCard: {
      background:   'var(--bg-card)',
      border:       '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-lg)',
      padding:      '28px',
      width:        '100%',
      maxWidth:     '400px',
    },
    fieldLabel: {
      fontSize:      11,
      fontFamily:    'var(--font-mono)',
      color:         'var(--text-muted)',
      letterSpacing: '0.08em',
      fontWeight:    700,
    },
    errorBox: {
      marginTop:    10,
      padding:      '8px 12px',
      background:   'var(--loss-dim)',
      border:       '1px solid var(--loss)',
      borderRadius: 'var(--radius-md)',
      color:        'var(--loss)',
      fontSize:     12,
      fontFamily:   'var(--font-mono)',
    },
    successBox: {
      marginTop:    10,
      padding:      '8px 12px',
      background:   'var(--gain-dim)',
      border:       '1px solid var(--gain)',
      borderRadius: 'var(--radius-md)',
      color:        'var(--gain)',
      fontSize:     12,
      fontFamily:   'var(--font-mono)',
    },
}
  
export const stc = {
    card:    { padding: '20px', transition: 'var(--transition)' },
    iconRow: { marginBottom: 12 },
    icon: {
      width:          36,
      height:         36,
      borderRadius:   'var(--radius-md)',
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
    },
    value: {
      fontFamily:    'var(--font-mono)',
      fontWeight:    700,
      marginBottom:  4,
      letterSpacing: '-0.02em',
    },
    label: {
      fontSize:      11,
      color:         'var(--text-muted)',
      fontFamily:    'var(--font-mono)',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
    },
  }
  