
export const styles = {
    root: {
      minHeight:      '100vh',
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
      background:     'var(--bg-primary)',
      position:       'relative',
      overflow:       'hidden',
      padding:        '24px',
    },
    gridBg: {
      position:        'absolute',
      inset:           0,
      backgroundImage: `
        linear-gradient(var(--border-primary) 1px, transparent 1px),
        linear-gradient(90deg, var(--border-primary) 1px, transparent 1px)
      `,
      backgroundSize:  '40px 40px',
      opacity:         0.4,
      pointerEvents:   'none',
    },
    orb: {
      position:     'absolute',
      borderRadius: '50%',
      filter:       'blur(80px)',
      pointerEvents:'none',
      opacity:      0.15,
    },
    orbCyan: {
      width:      400,
      height:     400,
      background: 'var(--accent-cyan)',
      top:        '-10%',
      left:       '-10%',
    },
    orbAmber: {
      width:      300,
      height:     300,
      background: 'var(--accent-amber)',
      bottom:     '-10%',
      right:      '-5%',
    },
    themeBtn: {
      position:       'absolute',
      top:            24,
      right:          24,
      background:     'var(--bg-card)',
      border:         '1px solid var(--border-primary)',
      borderRadius:   '50%',
      width:          40,
      height:         40,
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
      cursor:         'pointer',
      transition:     'var(--transition)',
      zIndex:         10,
    },
    card: {
      position:     'relative',
      zIndex:       1,
      background:   'var(--bg-card)',
      border:       '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-xl)',
      padding:      '40px',
      width:        '100%',
      maxWidth:     '440px',
      boxShadow:    'var(--shadow-card), var(--shadow-glow-cyan)',
    },
    logoRow: {
      display:      'flex',
      alignItems:   'center',
      gap:          10,
      marginBottom: 28,
    },
    logoIcon: {
      width:          40,
      height:         40,
      background:     'var(--accent-cyan)',
      borderRadius:   'var(--radius-md)',
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
      boxShadow:      'var(--shadow-glow-cyan)',
    },
    logoText: {
      fontFamily:    'var(--font-display)',
      fontSize:      22,
      fontWeight:    800,
      color:         'var(--text-primary)',
      letterSpacing: '-0.03em',
    },
    stepRow: {
      display:     'flex',
      alignItems:  'flex-start',
      gap:         0,
      marginBottom: 28,
    },
    stepLine: {
      flex:       1,
      height:     2,
      background: 'var(--border-primary)',
      marginTop:  13,
    },
    title: {
      fontSize:      26,
      marginBottom:  6,
      letterSpacing: '-0.02em',
    },
    subtitle: {
      fontSize:     14,
      color:        'var(--text-secondary)',
      marginBottom: 24,
      fontFamily:   'var(--font-mono)',
    },
    errorBanner: {
      display:      'flex',
      alignItems:   'center',
      gap:          8,
      background:   'var(--loss-dim)',
      border:       '1px solid var(--loss)',
      borderRadius: 'var(--radius-md)',
      padding:      '10px 14px',
      color:        'var(--loss)',
      fontSize:     13,
      fontFamily:   'var(--font-mono)',
      marginBottom: 20,
    },
    form: {
      display:       'flex',
      flexDirection: 'column',
      gap:           18,
    },
    fieldGroup: {
      display:       'flex',
      flexDirection: 'column',
      gap:           6,
    },
    label: {
      fontSize:      11,
      fontFamily:    'var(--font-mono)',
      color:         'var(--text-muted)',
      letterSpacing: '0.1em',
      fontWeight:    700,
    },
    inputStyle: {
      width: '100%',
    },
    pwdWrapper: {
      position: 'relative',
    },
    eyeBtn: {
      position:   'absolute',
      right:      12,
      top:        '50%',
      transform:  'translateY(-50%)',
      background: 'none',
      border:     'none',
      cursor:     'pointer',
      padding:    4,
      display:    'flex',
      alignItems: 'center',
    },
    currencyIcon: {
      position:   'absolute',
      left:       12,
      top:        '50%',
      transform:  'translateY(-50%)',
      display:    'flex',
      alignItems: 'center',
      pointerEvents: 'none',
    },
    submitBtn: {
      width:          '100%',
      justifyContent: 'center',
      padding:        '14px',
      fontSize:       14,
    },
    quickAmounts: {
      display:   'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap:       8,
    },
    quickBtn: {
      background:    'var(--bg-input)',
      border:        '1px solid var(--border-primary)',
      borderRadius:  'var(--radius-md)',
      padding:       '8px 4px',
      fontSize:      11,
      fontFamily:    'var(--font-mono)',
      color:         'var(--text-secondary)',
      cursor:        'pointer',
      transition:    'var(--transition)',
      textAlign:     'center',
    },
    quickBtnActive: {
      borderColor: 'var(--accent-cyan)',
      color:       'var(--accent-cyan)',
      background:  'var(--accent-cyan-dim)',
    },
    marginPreview: {
      background:   'var(--accent-cyan-dim)',
      border:       '1px solid var(--border-accent)',
      borderRadius: 'var(--radius-md)',
      padding:      '14px 16px',
      display:      'flex',
      flexDirection:'column',
      gap:          8,
    },
    marginRow: {
      display:        'flex',
      justifyContent: 'space-between',
      alignItems:     'center',
    },
    marginLabel: {
      fontSize:   12,
      fontFamily: 'var(--font-mono)',
      color:      'var(--text-muted)',
    },
    marginValue: {
      fontSize:   13,
      fontFamily: 'var(--font-mono)',
      fontWeight: 700,
      color:      'var(--text-primary)',
    },
    registerText: {
      textAlign:  'center',
      fontSize:   13,
      color:      'var(--text-secondary)',
      fontFamily: 'var(--font-mono)',
    },
    link: {
      color:          'var(--accent-cyan)',
      textDecoration: 'none',
      fontWeight:     700,
    },
    spinner: {
      width:        16,
      height:       16,
      border:       '2px solid rgba(0,0,0,0.2)',
      borderTop:    '2px solid var(--bg-primary)',
      borderRadius: '50%',
      display:      'inline-block',
      animation:    'spin 0.8s linear infinite',
    },
  }